-- Records left behind when their session was deleted still contain the old
-- session-prefixed name. The service-role cleanup worker must delete the object,
-- then delete this cleanup record; retain it as the durable cleanup obligation.
